name: build-dotnet
on:
  workflow_call:
    # Introduced 'inputs' to define parameters that can be passed when calling this workflow
    inputs:
      project:
        description: "Node version"
        required: true
        type: string
jobs: 
  build-dotnet:
    runs-on: ubuntu-latest
    steps: 
      # check out
      - name: checkout repo
        uses: actions/checkout@v4
       # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

